#!/usr/bin/env bash
# script that transfers a file from our client to a server
# check for command line arguments

if [ $# -lt 4]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# assign variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disable strict host checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@ip:~/"

# check for file transfer success
if [ $? -eq 0 ]
then
        echo "File Transfer successful"
else
        echo "File Transfer Failed"
fi
