#!/usr/bin/env bash
# script displays Best School 10 times, but for the 9th, displays Best School and then Hi.
i=0
while ((i < 10))
do
	echo "Best School"
	((i++))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
